# 10/4/2023
# V13.3.2

name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  common:
    name: Set up Runners
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ Windows-latest, macOS-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero

  server:
    name: Server-side Testing (On 3 Operating systems)
    needs: common
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ Windows-latest, macOS-latest, ubuntu-latest ]
    steps:
      - name: Execute pytest
        run: |
          pytest test_server.py

  client:
    name: Client-side Testing (On 3 Operating systems)
    needs: common
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ Windows-latest, macOS-latest, ubuntu-latest ]
    steps:
      - name: Execute pytest
        run: |
          pytest test_client.py
