# 4/4/2023
# V13.3.2

name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  job1:
    name: Server-side Testing (Windows-latest on Python 3.11.2)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
      - name: Execute pytest
        run: |
          pytest test_server.py
  job2:
    name: Client-side Testing (Windows-latest on Python 3.11.2)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
      - name: Execute pytest
        run: |
          pytest test_client.py
  job3:
    name: Server-side Testing (macOS-latest on Python 3.11.2)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
      - name: Execute pytest
        run: |
          pytest test_server.py
  job4:
    name: Client-side Testing (macOS-latest on Python 3.11.2)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
      - name: Execute pytest
        run: |
          pytest test_client.py
  job5:
    name: Server-side Testing (ubuntu-latest on Python 3.11.2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute pytest
        run: |
          pytest test_server.py
  job6:
    name: Client-side Testing (ubuntu-latest on Python 3.11.2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest colorutils guizero
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute pytest
        run: |
          pytest test_client.py
